### ISSUE TITLE
Upload Image Error in Test

### ISSUE THREAD

**Issue by chriscarducci** [CS673Smr16Team1/project#10]
![image](https://cloud.githubusercontent.com/assets/16747109/16252601/ab20fee0-37fd-11e6-8fb9-9b41e4471ea6.png)

**Comment by chriscarducci** [comment]
Just realized, I forgot to choose a file before clicking upload (I thought that clicking Upload would result in a popup to choose a file). Should check for a blank/null filename and alert user.

**Comment by jak464** [comment]
thanks Chris. I updated the code to disable that upload box until an image is uploaded. you can retry it now when you get a moment
