### ISSUE TITLE
Queued: Project story - Status and Priority fields are static

### ISSUE THREAD

**Issue by srivathsar** [CS673Smr16Team1/project#2]
Create a story under a project.
The status is always set to "New"
The priority is always set to "Low"
Stories created with other values are not saved as such
Edit doesn't reflect either

**Comment by sangDev** [comment]
fixed this issue. updated views and js for handling save and detail view

**Comment by sangDev** [comment]
fixed this issue. updated views and js for handling save and detail view 
https://github.com/CS673Smr16Team1/project/commit/650e1561af1b8554dea00aa7239040eaa4db469f
