### ISSUE TITLE
Queued: [UI] - Status and Priority dropdowns under Project story

### ISSUE THREAD

**Issue by srivathsar** [CS673Smr16Team1/project#3]
- Minor UI issue *
  ![dropdown_ui](https://cloud.githubusercontent.com/assets/12011093/16060655/ebb013d0-3256-11e6-8499-1b62c3274b24.jpg)

The UI of Status and Priority drop downs are slightly off. (check borders)

**Comment by sangDev** [comment]
Menu list has been updated and button location updated. This can be set as closed.
